name: Send Message to Telegram

on:
  schedule:
    - cron: '5 9 * * 6'  # 每周六早上 9:05 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 使用合适的 Python 版本

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run login.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CUSTOM_MESSAGE: ${{ secrets.CUSTOM_MESSAGE }}
        run: |
          python reminder.py
